language: java 
jdk:
  - openjdk8
  - openjdk9

env:
  matrix
  - COVERAGE=0.5 TARGET=ui
  - COVERAGE=0.5 TARGET=service/cart
  - COVERAGE=0.5 TARGET=service/user

  - COVERAGE=0.5 TARGET=repository/order
  - COVERAGE=0.5 TARGET=repository/cart
  - COVERAGE=0.5 TARGET=repository/product
  - COVERAGE=0.5 TARGET=repository/user

intall:
  - ./gradlew clean jar

script:
  - echo "testing coming soon"
  - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check

jobs:
  include:
    stage: deploy
    before_deploy:
      - ./gradlew -p ./monolithic/ui packageToContainer
    deploy:
      - provider: script
        script: ./script/deploy.sh
        on:
          branch: master
