language: java 
jdk: openjdk8
env:
  - COVERAGE=0.5 TARGET=ui
  - COVERAGE=0.5 TARGET=service/cart
  - COVERAGE=0.5 TARGET=service/user

  - COVERAGE=0.5 TARGET=repository/order
  - COVERAGE=0.5 TARGET=repository/cart
  - COVERAGE=0.5 TARGET=repository/product
  - COVERAGE=0.5 TARGET=repository/user

intall:
  - ./gradlew clean jar

script:
  - echo "testing coming soon"
  - COVERAGE=$COVERAGE ./gradlew -p ./monolithic/$TARGET check

deploy:
  - provider: script
    script: echo "WIP"
    on:
      all_branches: true
